name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Print previous ulimit -l
      run: ulimit -l
    - name: Raise ulimit on locked memory
      run: ulimit -l 40960
    - name: Install nightly
      run: rustup install nightly
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --verbose
